Marrwie/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Marrwie.Entities;
using Microsoft.AspNet.Identity;
using Marrwie.Models;
using System.IO;

namespace Marrwie.Controllers
{
    [Authorize(Roles = "admin,user")]
    public class ArticleController : Controller
    {
        private MarrwieDbContext db = new MarrwieDbContext();

        public ActionResult Index()
        {
            var model = db.Articles.ToList().Select(p => new ArticleViewModel{ Id = p.Id, ArticleCategoriesString = string.Join(",", p.Categories.Select(t => t.Name).ToList()), CreatedDate = p.CreatedDate, CreatedUserId = p.CreatedUserId, CreatedUserName = p.CreatedUserName, Desciption = p.Desciption, Title = p.Title, UpdatedDate = p.UpdatedDate, IsAuthorizedForEdit = p.CreatedUserId == User.Identity.GetUserId(), IsAuthorizedForDelete = p.CreatedUserId == User.Identity.GetUserId(), IsAuthorizedForDetails = p.CreatedUserId == User.Identity.GetUserId(), IsAuthorizedForApprove = User.IsInRole("admin") && !p.IsApproved, IsApproved = p.IsApproved }).ToList();
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult GetArticlesForCategory(int id, int pageNumber=1)
        {
            var model = new HomeViewModel();
            model.Articles = new List<ArticleViewModel>();

            foreach (var art in db.Articles.Where(p => p.IsApproved && p.Categories.Select(t => t.Id).Contains(id)).ToList().OrderByDescending(p => p.Id).Skip((pageNumber - 1) * 10).Take(10).ToList())
            {
                var articleModel = new ArticleViewModel();
                articleModel.Id = art.Id;
                articleModel.CreatedDate = art.CreatedDate;
                articleModel.CreatedUserId = art.CreatedUserId;
                articleModel.CreatedUserName = art.CreatedUserName;
                articleModel.Desciption = art.Desciption;
                articleModel.Title = art.Title;
                articleModel.UpdatedDate = art.UpdatedDate;
                articleModel.ArticleCategoriesString = string.Join(",", art.Categories.Select(p => p.Name).ToList());
                model.Articles.Add(articleModel);
            }
            model.TotalPageNumber = db.Articles.Where(p => p.Categories.Select(t => t.Id).Contains(id)).ToList().Count() != 0 ? (int)Math.Ceiling(db.Articles.Where(p => p.Categories.Select(t => t.Id).Contains(id)).ToList().Count() / 10d) : 0;
            model.CurrentPageNumber = pageNumber;
            model.CategoryId = id;
            return View(model);
        }

        public ActionResult GetAllArticles()
        {
            var model = db.Articles.ToList().Select(p => new ArticleViewModel { Id = p.Id, ArticleCategoriesString = string.Join(",", p.Categories.Select(t => t.Name).ToList()), CreatedDate = p.CreatedDate, CreatedUserId = p.CreatedUserId, CreatedUserName = p.CreatedUserName, Desciption = p.Desciption, Title = p.Title, UpdatedDate = p.UpdatedDate}).ToList();
            return View(model);
        }

        public ActionResult GetArticlesOfUser(string id)
        {
            var model = db.Articles.Where(p => p.CreatedUserId == id).ToList().Select(p => new ArticleViewModel { Id = p.Id, ArticleCategoriesString = string.Join(",", p.Categories.Select(t => t.Name).ToList()), CreatedDate = p.CreatedDate, CreatedUserId = p.CreatedUserId, CreatedUserName = p.CreatedUserName, Desciption = p.Desciption, Title = p.Title, UpdatedDate = p.UpdatedDate}).ToList();
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult GetArticle(int id)
        {
            var article = db.Articles.Find(id);
            var model = new ArticleViewModel { ArticleCategoriesString = string.Join(",", article.Categories.ToList()), CreatedDate = article.CreatedDate, Id = article.Id, CreatedUserId = article.CreatedUserId, CreatedUserName = article.CreatedUserName, Desciption = article.Desciption, Title = article.Title, UpdatedDate = article.UpdatedDate };
            return View(model);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        public ActionResult Create()
        {
            var model = new ArticleViewModel();
            model.ArticleCategories = new List<ArticleCategoriesViewModel>();

            foreach (var cat in db.Categories)
                model.ArticleCategories.Add(new ArticleCategoriesViewModel() { Id = cat.Id, HasGot = false, Name = cat.Name });
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var article = new Article();
                article.CreatedUserId = User.Identity.GetUserId();
                article.CreatedUserName = User.Identity.GetUserName();
                article.CreatedDate = DateTime.Now;
                article.UpdatedDate = DateTime.Now;
                article.Desciption = model.Desciption;
                article.Title = model.Title;
                article.IsApproved = false;

                var addedCategoryIds = model.ArticleCategories.Where(p => p.HasGot).Select(p => p.Id).ToList().Except(article.Categories.Select(p => p.Id).ToList()).ToList();

                foreach (var addedCategoryId in addedCategoryIds)
                {
                    article.Categories.Add(db.Categories.Find(addedCategoryId));
                }

                
                if (model.ArticleFiles.Count > 0)
                {
                    if(model.ArticleFiles.FirstOrDefault() != null) { 
                        
                        foreach (var artFile in model.ArticleFiles)
                        {
                            Guid guid = Guid.NewGuid();
                            string ext = Path.GetExtension(artFile.FileName);
                            string name = Path.GetFileNameWithoutExtension(artFile.FileName);
                            article.ArticleFiles.Add(new ArticleFile()
                            {
                                MimeType = artFile.ContentType,
                                Ext = ext,
                                Name = name,
                                RowName = guid
                            }); ;

                            var path = Server.MapPath("/Images");
                            if (!Directory.Exists(path))
                                Directory.CreateDirectory(path);

                            var fullPath = string.Format(@"{0}\{1}{2}", path, guid, ext);
                            artFile.SaveAs(fullPath);
                        }
                    }
                }

                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Article article = db.Articles.Find(id);

            

            var model = new ArticleViewModel();
            model.CreatedDate = article.CreatedDate;
            model.CreatedUserId = article.CreatedUserId;
            model.CreatedUserName = article.CreatedUserName;
            model.Desciption = article.Desciption;
            model.Id = article.Id;
            model.Title = article.Title;
            model.UpdatedDate = article.UpdatedDate;

            model.ArticleCategories = new List<ArticleCategoriesViewModel>();

            foreach (var cat in db.Categories.ToList())
            {
                if (article.Categories.Select(p => p.Id).Contains(cat.Id))
                    model.ArticleCategories.Add(new ArticleCategoriesViewModel() { Id = cat.Id, HasGot = true, Name = cat.Name });
                else
                    model.ArticleCategories.Add(new ArticleCategoriesViewModel() { Id = cat.Id, HasGot = false, Name = cat.Name });
            }
            if (article == null)
            {
                return HttpNotFound();
            }

            if (article.CreatedUserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var article = db.Articles.Find(model.Id);
                article.UpdatedDate = DateTime.Now;
                article.Desciption = model.Desciption;
                article.Title = model.Title;
                article.IsApproved = false;

                var addedCategoryIds = model.ArticleCategories.Where(p => p.HasGot).Select(p => p.Id).ToList().Except(article.Categories.Select(p => p.Id).ToList()).ToList();
                var deletedCategoryIds = article.Categories.Select(p => p.Id).ToList().Except(model.ArticleCategories.Where(p => p.HasGot).Select(p => p.Id).ToList()).ToList();

                foreach (var addedCategoryId in addedCategoryIds)
                {
                    article.Categories.Add(db.Categories.Find(addedCategoryId));
                }

                foreach (var deletedCategoryId in deletedCategoryIds)
                {
                    article.Categories.Remove(db.Categories.Find(deletedCategoryId));
                }

Marrwie/Controllers/LogController.cs
using Marrwie.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marrwie.Controllers
{
    public class LogController : Controller
    {
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var path = Server.MapPath(LogHelper.LogFolder);
            var fullPath = FileHelper.CheckLogFile(path);
            ViewBag.Logs = System.IO.File.ReadAllText(fullPath);
            return View();
        }
    }
}

Marrwie/Controllers/RoleController.cs
using Marrwie.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Marrwie.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoleController : Controller
    {
        private RoleManager<ApplicationRole> _roleManager;

        public RoleController()
        {
            _roleManager = new Microsoft.AspNet.Identity.RoleManager<ApplicationRole>(new RoleStore<ApplicationRole>(new ApplicationDbContext()));
        }

        public ActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }

        [Authorize(Roles ="admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _roleManager.CreateAsync(new ApplicationRole() { Name = model.Name, Description = model.Description });
                return RedirectToAction("Index");
            }
            
            return View(model);
        }


    }
}

Marrwie/Controllers/UserController.cs
using Marrwie.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marrwie.Controllers
{
    [Authorize(Roles ="admin")]
    public class UserController : Controller
    {
        private UserManager<ApplicationUser> _userManager;

        public UserController()
        {
            _userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
        }

        public ActionResult Index()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }
    }
}

Marrwie/Views/Shared/_CategoryPartial.cshtml
@{ 
    var db = new Marrwie.Entities.MarrwieDbContext();
}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Kategoriler
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
        @foreach (var category in db.Categories.ToList())
        {
            <a class="dropdown-item" href="@Url.Action("GetArticlesForCategory", "Article", new { id = category.Id })">@category.Name</a>
        }
    </div>
</li>

Marrwie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Erdem Özşahin'in yazılım blogu</title>
    <meta name="keywords" content="C#, Sql Server, Ajax">
    <meta name="description" content="Yazılım Blogu" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js" integrity="sha512-WNLxfP/8cVYL9sj8Jnp6et0BkubLP31jhTG9vhL/F5uEZmg5wEzKoXp1kJslzPQWwPT1eyMiSxlKCgzHLOTOTQ==" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index","Home")">Yazılım Blogu</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index","Home")">Anasayfa <span class="sr-only">(current)</span></a>
                    </li>

                    @Html.Partial("_CategoryPartial")
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin Panel
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            @if (User.IsInRole("admin"))
                            {
                                <a class="dropdown-item" href="@Url.Action("Index", "Category")">Kategori</a>
                            }
                            @if (User.IsInRole("admin") || User.IsInRole("user"))
                            {
                                <a class="dropdown-item" href="@Url.Action("Index", "Article")">Makale</a>
                            }
                            @if (User.IsInRole("admin"))
                            {
                                <a class="dropdown-item" href="@Url.Action("Index", "User")">Kullanıcılar</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Role")">Roller</a>
                                <a class="dropdown-item" href="@Url.Action("GetUsersToAddRole", "Account")">Yetkiler</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Log")">Log</a>
                            }
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://github.com/erdemozs/erdemozsahinpublic.com">Git Hub(Source Code)</a>
                    </li>
                </ul>
            </div>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - erdemozsahin.com</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>